export const BASE_URL = "/api";

export const backgroundCards = [
  {
    id: 1,
    name: "Rahul",
    age: 24,
    gender: "male",
    description: "Building scalable backend systems. Let's talk APIs.",
    skills: ["Node.js", "Express", "MongoDB"],
    img: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: 2,
    name: "Sneha",
    age: 27,
    gender: "female",
    description: "Frontend architect obsessed with perfect UI/UX.",
    skills: ["React", "Tailwind", "Figma"],
    img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: 3,
    name: "Amit",
    age: 22,
    gender: "male",
    description: "Competitive programmer. Can invert a binary tree.",
    skills: ["C++", "Python", "Algorithms"],
    img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: 4,
    name: "Priya",
    age: 26,
    gender: "female",
    description: "Data scientist working on LLMs and AI agents.",
    skills: ["Python", "PyTorch", "SQL"],
    img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: 5,
    name: "Vikram",
    age: 25,
    gender: "male",
    description: "DevOps wizard. Dockerizing everything I touch.",
    skills: ["Docker", "AWS", "Kubernetes"],
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: 6,
    name: "Anjali",
    age: 23,
    gender: "female",
    description: "Fullstack dev looking for a hackathon team.",
    skills: ["Next.js", "Prisma", "TypeScript"],
    img: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: 7,
    name: "Karan",
    age: 28,
    gender: "male",
    description: "Building the next big SaaS platform.",
    skills: ["Vue", "Firebase", "Stripe"],
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: 8,
    name: "Neha",
    age: 21,
    gender: "female",
    description: "Just started my tech journey! Learning to code.",
    skills: ["HTML", "CSS", "JavaScript"],
    img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
  },
];
